
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubh
 */
public class Add_New_Tile extends javax.swing.JFrame {

    /**
     * Creates new form Add_New_Tile
     */
    public Add_New_Tile() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Type_Choice = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Adding New Tiles");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(589, 71, 230, 35);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(596, 138, 60, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(590, 220, 60, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Size");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(596, 173, 50, 21);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(661, 137, 141, 30);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(661, 172, 141, 30);

        button1.setLabel("Add Tile");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(700, 300, 122, 24);

        button2.setLabel("Back");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(570, 300, 122, 24);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Rate");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 260, 50, 21);

        jTextField4.setText("0");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(660, 260, 140, 30);

        Type_Choice.add(jRadioButton1);
        jRadioButton1.setText("Matt");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(660, 220, 80, 23);

        Type_Choice.add(jRadioButton2);
        jRadioButton2.setText("Glowsy");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(760, 220, 60, 23);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amigo/Photos/background5 (4).jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1400, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        Add_New_Tile.this.setVisible(false);
        Tiles_HomePage TH=new Tiles_HomePage();
        TH.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String Tname=jTextField1.getText();
        String Siz=jTextField2.getText();
        String rat=jTextField4.getText();
        //System.out.println(Siz.charAt(1));
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/amigo","root","Sahilgmail@12");

        if(Tname.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Name Is Empty");
        }
        else
        {
            if(Siz.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Size Is Empty");
            }
            else
            {
                    if(Siz.length()>2 && Siz.length()<4)
                    {
                        if(Siz.charAt(0)=='1' || Siz.charAt(0)=='2' || Siz.charAt(0)=='3' || Siz.charAt(0)=='4' || Siz.charAt(0)=='5' || Siz.charAt(0)=='6' || Siz.charAt(0)=='7' || Siz.charAt(0)=='8' || Siz.charAt(0)=='9' || Siz.charAt(0)=='0')
                        {
                            if( Siz.charAt(1)=='X')
                            {
                                if(Siz.charAt(2)=='1' || Siz.charAt(2)=='2' || Siz.charAt(2)=='3' || Siz.charAt(2)=='4' || Siz.charAt(2)=='5' || Siz.charAt(2)=='6' || Siz.charAt(2)=='7' || Siz.charAt(2)=='8' || Siz.charAt(2)=='9' || Siz.charAt(2)=='0')   
                                {
                                    if(rat.isEmpty())
                                    {
                                        JOptionPane.showMessageDialog(this,"Rate Is Empty");
                                    }
                                    else
                                    {
                                    if(jRadioButton1.isSelected())
                                    {
                                        String query1="insert into Tiles values(null,?,?,?,?)";
                                        PreparedStatement statement1 = conn.prepareStatement(query1);
                                        statement1.setString(1, Tname);
                                        statement1.setString(2, Siz);
                                        statement1.setString(3, "Matt");
                                        statement1.setString(4, rat);
                                        boolean r1=statement1.execute();
                                        if (r1=true){
                                            JOptionPane.showMessageDialog(null,"Successful");
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(null,"UnSuccessful");
                                        }
                                    }
                                    else
                                    {
                                        if(jRadioButton2.isSelected())
                                        {
                                            String query1="insert into Tiles values(null,?,?,?,?)";
                                            PreparedStatement statement1 = conn.prepareStatement(query1);
                                            statement1.setString(1, Tname);
                                            statement1.setString(2, Siz);
                                            statement1.setString(3, "Glowsy");
                                            statement1.setString(4, rat);
                                            boolean r1=statement1.execute();
                                            if (r1=true){
                                                JOptionPane.showMessageDialog(null,"Successful");
                                            }
                                            else
                                            {
                                                JOptionPane.showMessageDialog(null,"UnSuccessful");
                                            }
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(null,"Check Type Of Tile");
                                        }
                                    }
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null,"3rd Letter Should Be A Number");
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"Use X between Tile Size eg 4X4");
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"1st Letter Should Be A Number");
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Length Of Size Should Be 3");
                    }
                    }                   
                }
            }
            catch (SQLException ex) 
            {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } 
    }//GEN-LAST:event_button1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c))
        {
            jTextField1.setEditable(true);
        }
        else
        {
            jTextField1.setEditable(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c))
        {
            jTextField4.setEditable(true);
        }
        else
        {
            jTextField4.setEditable(false);
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c))
        {
            jTextField2.setEditable(true);
        }
        else
        {
            jTextField2.setEditable(false);
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_New_Tile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_New_Tile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_New_Tile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_New_Tile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_New_Tile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Type_Choice;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
