
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubh
 */
public class Add_New_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Add_New_Customer
     */
    public Add_New_Customer() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MOP_Choice = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(611, 95, 60, 21);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(718, 92, 150, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Address");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(611, 130, 70, 21);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(718, 130, 210, 80);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Contact Information");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(548, 223, 160, 21);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(718, 220, 140, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Mode Of Payment");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 270, 140, 21);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 380, 117, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 380, 112, 23);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("Adding New Customer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 50, 240, 26);

        MOP_Choice.add(jRadioButton1);
        jRadioButton1.setText("Cash");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(720, 270, 110, 23);

        MOP_Choice.add(jRadioButton2);
        jRadioButton2.setText("Cheque");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(720, 310, 110, 23);

        MOP_Choice.add(jRadioButton3);
        jRadioButton3.setText("Card");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(720, 350, 110, 23);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amigo/Photos/background5 (4).jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1380, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nme=jTextField1.getText();
        String addr=jTextArea1.getText();
        String cont=jTextField2.getText();
        if(nme.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Name Is Empty");
        }
        else
        {
            if(addr.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Address Is Empty");
            }
            else
            {
                if(cont.isEmpty())
                {
                    JOptionPane.showMessageDialog(null,"Contact Is Empty");
                }
                else
                {
                    if(cont.length()==10)
                    {
                        Connection conn;
                        try {
                            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/amigo","root","Sahilgmail@12");
                            if(jRadioButton1.isSelected())
                            {
                                String query1="insert into Customer values(null,?,?,?,?)";
                                PreparedStatement statement1 = conn.prepareStatement(query1);
                                statement1.setString(1, nme);
                                statement1.setString(2, "Cash");
                                statement1.setString(3, cont);
                                statement1.setString(4, addr);
                                boolean r1=statement1.execute();
                                if (r1=true){
                                    JOptionPane.showMessageDialog(null,"Successful");
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null,"UnSuccessful");
                                }
                            }
                            else
                            {
                                if(jRadioButton2.isSelected())
                                {
                                    String query1="insert into Customer values(null,?,?,?,?)";
                                    PreparedStatement statement1 = conn.prepareStatement(query1);
                                    statement1.setString(1, nme);
                                    statement1.setString(2, "Cheque");
                                    statement1.setString(3, cont);
                                    statement1.setString(4, addr);
                                    boolean r1=statement1.execute();
                                    if (r1=true){
                                        JOptionPane.showMessageDialog(null,"Successful");
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null,"UnSuccessful");
                                    }                                
                                }
                                else
                                {
                                    if(jRadioButton3.isSelected())
                                    {
                                        String query1="insert into Customer values(null,?,?,?,?)";
                                        PreparedStatement statement1 = conn.prepareStatement(query1);
                                        statement1.setString(1, nme);
                                        statement1.setString(2, "Card");
                                        statement1.setString(3, cont);
                                        statement1.setString(4, addr);
                                        boolean r1=statement1.execute();
                                        if (r1=true){
                                            JOptionPane.showMessageDialog(null,"Successful");
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(null,"UnSuccessful");
                                        }                                    
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null,"Mode Of Payment Not Selected");
                                    }
                                }
                            }
                        }catch (SQLException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                         }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Check Contact Info Again");
                    }
                }
            }
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Add_New_Customer.this.setVisible(false);
        Customer_HomePage home=new Customer_HomePage();
        home.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c))
        {
            jTextField1.setEditable(true);
        }
        else
        {
            jTextField1.setEditable(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c)|| Character.isISOControl(c))
        {
            jTextField2.setEditable(true);
        }
        else
        {
            jTextField2.setEditable(false);
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_New_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_New_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_New_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_New_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_New_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup MOP_Choice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
