
import java.awt.Dimension;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;  
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubh
 */
public class GenerateBill extends javax.swing.JFrame {

    /**
     * Creates new form GenerateBill
     */
    public GenerateBill() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Recipt = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Customer Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 230, 130, 21);

        txtCustomerName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtCustomerName);
        txtCustomerName.setBounds(350, 230, 110, 25);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Delivery Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 260, 110, 21);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 340, 90, 23);

        Recipt.setColumns(20);
        Recipt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Recipt.setLineWrap(true);
        Recipt.setRows(5);
        jScrollPane1.setViewportView(Recipt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(700, 0, 660, 720);

        jTextField1.setText("0");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(350, 300, 110, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Transport Charges");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 300, 150, 21);

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 370, 90, 23);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 400, 90, 23);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(350, 260, 110, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amigo/Photos/background5 (4).jpg"))); // NOI18N
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1380, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            // TODO add your handling code here:
            
            String customer_name=txtCustomerName.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String DD;
            String ti;
            String ty;
            String CN;
            int Cid=0;
            int rat=0;
            int NOFT=0;
            int NOFTXrat;
            int TotalBill=0;
            double TotalBillAfterTransportCharges=0;
            double CGST=0;
            double SGST=0;
            double FinalBill=0;
            int TransportCharges=Integer.valueOf(jTextField1.getText());
            List<Integer> TotalBillElements = new ArrayList<>();
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
            Date date = new Date();  
            if(customer_name.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Name Is Empty");
            }
            else
            {
                if(jDateChooser1.getDate()!=null)
                {
                    DD= sdf.format(jDateChooser1.getDate());
                    Connection conn;
                    try {
                        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/amigo","root","Sahilgmail@12");
                        String query1="select name,address,cid from customer where name=?";
                        PreparedStatement statement1 = conn.prepareStatement(query1);
                        statement1.setString(1, customer_name);
                        ResultSet result = statement1.executeQuery();
                        while(result.next())
                        {
                            CN=result.getString("name");    
                            String Addr=result.getString("Address");
                            Cid=result.getInt("cid");
                            Recipt.setText("                                                  Amigo Ceramica\n                                                            31 J. LAXMI INDUSTRIAL ESTATE,\n                                                                New Link Rd, Andheri West,\n                                                                Mumbai, Maharashtra 400053\n \n"+"Customer Name: "+CN+"\nAddress: "+Addr+"\n_______________________________________________________\n");
                        }
                        String query2="select tiles.*,orders.* from tiles,orders where tiles.tid=orders.Tid and orders.cid=? and orders.Delivery_Date=?";
                        PreparedStatement statement2 = conn.prepareStatement(query2);
                        statement2.setInt(1,Cid);
                        statement2.setString(2,DD);
                        ResultSet result2 = statement2.executeQuery();
                        while(result2.next())
                        {
                            ti=result2.getString("name");
                            ty=result2.getString("type");
                            NOFT=result2.getInt("Number_Of_Tiles");
                            rat=result2.getInt("Rate");
                            NOFTXrat=NOFT*rat;
                            TotalBillElements.add(NOFTXrat);
                            Recipt.setText(Recipt.getText()+"Name Of Tiles:"+ti+"\n"+"Type:"+ty+"\n"+"Number Of Tiles:"+NOFT+"\nRate:"+rat+"\nTotal Cost:"+NOFTXrat+"\n---------------------------------\n");
                        }
                        for(int i=0;i<TotalBillElements.size();i++)
                        {
                            TotalBill+=TotalBillElements.get(i);
                        }
                        TotalBillAfterTransportCharges=TotalBill+TransportCharges;
                        CGST=TotalBillAfterTransportCharges*0.09;
                        SGST=TotalBillAfterTransportCharges*0.09;
                        FinalBill=TotalBillAfterTransportCharges+CGST+SGST;

                        Recipt.setText(Recipt.getText()+"_______________________________________________________\n"+"Total Of All Tiles:"+TotalBill+"\n_______________________________________________________"+"\nTransportCharges:"+TransportCharges+"\nCSGT:"+CGST+"\nSGST:"+SGST+"\n_______________________________________________________"+"\nGrand Total:"+FinalBill);

                        Recipt.setText(Recipt.getText()+"\n"+"\n"+"\n------------------------X-------------------------X-----------------------------X---------"+"\n                                            Thank You For Visiting \n                                            Happy Shoping \n                                            Come Again Soon\n\nContact Number: 022-49705657     Email: amigoceramica@gmail.com\n\nThis Is A Computer Generated Recipt Create On "+formatter.format(date));

                        conn.close();
                    } catch (SQLException ex) {
                    Logger.getLogger(GenerateBill.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Select Delivery Date");
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Recipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(GenerateBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        GenerateBill.this.setVisible(false);
        The_HomePage TH=new The_HomePage();
        TH.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCustomerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c))
        {
            txtCustomerName.setEditable(true);
        }
        else
        {
            txtCustomerName.setEditable(false);
        }
    }//GEN-LAST:event_txtCustomerNameKeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
                char c=evt.getKeyChar();
        if(Character.isDigit(c) ||  Character.isISOControl(c))
        {
            jTextField1.setEditable(true);
        }
        else
        {
            jTextField1.setEditable(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Recipt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables
}
