
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubh
 */
public class View_Tiles extends javax.swing.JFrame {

    /**
     * Creates new form View_Tiles
     */
    public View_Tiles() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tid", "Name", "Size", "Type", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("ShowData");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Type");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jRadioButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton3KeyPressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Size");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jRadioButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton2KeyPressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Name");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jRadioButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton1KeyPressed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Tid");

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "TID", "Size", "Type", "Rate" }));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Rate");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jRadioButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton4KeyPressed(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRadioButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRadioButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(151, 151, 151)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        View_Tiles.this.setVisible(false);
        Tiles_HomePage TH=new Tiles_HomePage();
        TH.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tid;
        String nam;
        String siz;
        String typ;
        String rat;

        Connection conn;
        DefaultTableModel tblModel;
        tblModel =(DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/amigo","root","Sahilgmail@12");
            String query1="select * from Tiles";
            PreparedStatement statement = conn.prepareStatement(query1);
            ResultSet result = statement.executeQuery();
            while(result.next())
            {
                tid=String.valueOf(result.getInt("Tid"));
                nam=result.getString("Name");
                siz=result.getString("Size");
                typ=result.getString("Type");
                rat=result.getString("rate");
                String tbData[]={tid,nam,siz,typ,rat};
                tblModel.addRow(tbData);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String info1=jTextField1.getText();
        String info2=jTextField2.getText();
        String info3;
        Connection conn;
        if(info1.isEmpty() || info2.isEmpty())
        {
                JOptionPane.showMessageDialog(null,"Enter Data In The Box");
        }
        else{
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/amigo","root","Sahilgmail@12");
            if(info2.length()!=0)
            {
                if(jRadioButton1.isSelected())
                {
                    String query1="Update Tiles set Name='"+info2+"'  where tid=?";
                    PreparedStatement statement1 = conn.prepareStatement(query1);
                    statement1.setString(1, info1);
                    boolean r1=statement1.execute();
                    if (r1=true){
                        JOptionPane.showMessageDialog(null,"Successful");
                        DefaultTableModel tblModel;
                        tblModel =(DefaultTableModel)jTable1.getModel();
                        tblModel.setRowCount(0);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"UnSuccessful");
                    }    
                }
                if(jRadioButton2.isSelected())
                {
                    if(info2.length()>2 && info2.length()<4)
                    {
                        if(info2.charAt(0)=='1' || info2.charAt(0)=='2' || info2.charAt(0)=='3' || info2.charAt(0)=='4' || info2.charAt(0)=='5' || info2.charAt(0)=='6' || info2.charAt(0)=='7' || info2.charAt(0)=='8' || info2.charAt(0)=='9' || info2.charAt(0)=='0')
                        {
                            if( info2.charAt(1)=='X')
                            {
                                if(info2.charAt(2)=='1' || info2.charAt(2)=='2' || info2.charAt(2)=='3' || info2.charAt(2)=='4' || info2.charAt(2)=='5' || info2.charAt(2)=='6' || info2.charAt(2)=='7' || info2.charAt(2)=='8' || info2.charAt(2)=='9' || info2.charAt(2)=='0')   
                                {
                                    String query1="Update Tiles set Size='"+info2+"'  where tid=?";
                                    PreparedStatement statement1 = conn.prepareStatement(query1);
                                    statement1.setString(1, info1);
                                    boolean r1=statement1.execute();
                                    if (r1=true){
                                        JOptionPane.showMessageDialog(null,"Successful");
                                        DefaultTableModel tblModel;
                                        tblModel =(DefaultTableModel)jTable1.getModel();
                                        tblModel.setRowCount(0);
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null,"UnSuccessful");
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null,"3rd value should be a number");
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"There should be X between size eg 4X4");
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"1st value should be a number");
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Check Size");
                    }                
                }
                if(jRadioButton3.isSelected())
                {
                    info3=info2.toLowerCase();
                    System.out.println(info3);
                    if(info3.equals("glowsy") || info3.equals("matt"))
                    {
                        String query1="Update Tiles set Type='"+info2+"'  where tid=?";
                        PreparedStatement statement1 = conn.prepareStatement(query1);
                        statement1.setString(1, info1);
                        boolean r1=statement1.execute();
                        if (r1=true){
                            JOptionPane.showMessageDialog(null,"Successful");
                            DefaultTableModel tblModel;
                            tblModel =(DefaultTableModel)jTable1.getModel();
                            tblModel.setRowCount(0);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"UnSuccessful");
                        }   
                    }
                    else
                    {
                            JOptionPane.showMessageDialog(null,"Choose Glowsy Or Matt");
                    }
                }
                if(jRadioButton4.isSelected())
                {
                    if(info2.length()!=0)
                    {
                        String query1="Update Tiles set Rate='"+info2+"'  where tid=?";
                        PreparedStatement statement1 = conn.prepareStatement(query1);
                        statement1.setString(1, info1);
                        boolean r1=statement1.execute();
                        if (r1=true){
                            JOptionPane.showMessageDialog(null,"Successful");
                            DefaultTableModel tblModel;
                            tblModel =(DefaultTableModel)jTable1.getModel();
                            tblModel.setRowCount(0);
                        }   
                        else
                        {
                            JOptionPane.showMessageDialog(null,"UnSuccessful");
                        }
                    }   
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Update Box Is Empty");
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String tid;
        String nam;
        String siz;
        String typ;
        String rat;
        String info1=jTextField3.getText();
        String CB=jComboBox1.getSelectedItem().toString();
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/amigo","root","Sahilgmail@12");
            if("Name".equals(CB))
            {
                
                String query1="Select * from Tiles where name=?";
                PreparedStatement statement1 = conn.prepareStatement(query1);
                statement1.setString(1, info1);
                ResultSet result = statement1.executeQuery();
                DefaultTableModel tblModel;
                tblModel =(DefaultTableModel)jTable1.getModel();
                tblModel.setRowCount(0);
                while(result.next())
                {
                    tid=String.valueOf(result.getInt("Tid"));
                    nam=result.getString("Name");
                    siz=result.getString("Size");
                    typ=result.getString("Type");
                    rat=result.getString("rate");
                    String tbData[]={tid,nam,siz,typ,rat};
                    tblModel.addRow(tbData);
                }
            }
            else
            {
                if("TID".equals(CB))
                {
                    String query1="Select * from Tiles where tid=?";
                    PreparedStatement statement1 = conn.prepareStatement(query1);
                    statement1.setString(1, info1);
                    ResultSet result = statement1.executeQuery();
                    DefaultTableModel tblModel;
                    tblModel =(DefaultTableModel)jTable1.getModel();
                    tblModel.setRowCount(0);
                    while(result.next())
                    {
                        tid=String.valueOf(result.getInt("Tid"));
                        nam=result.getString("Name");
                        siz=result.getString("Size");
                        typ=result.getString("Type");
                        rat=result.getString("rate");
                        String tbData[]={tid,nam,siz,typ,rat};
                        tblModel.addRow(tbData);
                    }
                }
                else
                {
                    if("Size".equals(CB))
                    {
                        String query1="Select * from Tiles where size=?";
                        PreparedStatement statement1 = conn.prepareStatement(query1);
                        statement1.setString(1, info1);
                        ResultSet result = statement1.executeQuery();
                        DefaultTableModel tblModel;
                        tblModel =(DefaultTableModel)jTable1.getModel();
                        tblModel.setRowCount(0);
                        while(result.next())
                        {
                            tid=String.valueOf(result.getInt("Tid"));
                            nam=result.getString("Name");
                            siz=result.getString("Size");
                            typ=result.getString("Type");
                            rat=result.getString("rate");
                            String tbData[]={tid,nam,siz,typ,rat};
                            tblModel.addRow(tbData);
                        }
                    }
                    else
                    {
                        if("Type".equals(CB))
                        {
                            String query1="Select * from Tiles where Type=?";
                            PreparedStatement statement1 = conn.prepareStatement(query1);
                            statement1.setString(1, info1);
                            ResultSet result = statement1.executeQuery();
                            DefaultTableModel tblModel;
                            tblModel =(DefaultTableModel)jTable1.getModel();
                            tblModel.setRowCount(0);
                            while(result.next())
                            {
                                tid=String.valueOf(result.getInt("Tid"));
                                nam=result.getString("Name");
                                siz=result.getString("Size");
                                typ=result.getString("Type");
                                rat=result.getString("rate");
                                String tbData[]={tid,nam,siz,typ,rat};
                                tblModel.addRow(tbData);
                            }
                        }
                        else
                        {
                            if("Rate".equals(CB))
                            {
                                String query1="Select * from Tiles where Rate=?";
                                PreparedStatement statement1 = conn.prepareStatement(query1);
                                statement1.setString(1, info1);
                                ResultSet result = statement1.executeQuery();
                                DefaultTableModel tblModel;
                                tblModel =(DefaultTableModel)jTable1.getModel();
                                tblModel.setRowCount(0);
                                while(result.next())
                                {
                                    tid=String.valueOf(result.getInt("Tid"));
                                    nam=result.getString("Name");
                                    siz=result.getString("Size");
                                    typ=result.getString("Type");
                                    rat=result.getString("rate");
                                    String tbData[]={tid,nam,siz,typ,rat};
                                    tblModel.addRow(tbData);
                                }
                            }
                        }
                    }    
                }    
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Connection conn;
        DefaultTableModel tblModel;
        tblModel =(DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();  
        try {
            if(jTable1.getSelectedRowCount()==1)
            {
                Object  j=jTable1.getModel().getValueAt(i,0);
                System.out.println(j);
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/amigo","root","Sahilgmail@12");    
                String sql = "DELETE FROM Tiles WHERE Tid = '"+j+"'";
                tblModel.removeRow(jTable1.getSelectedRow());
                PreparedStatement statement1 = conn.prepareStatement(sql);
                statement1.execute();
                JOptionPane.showMessageDialog(this,"Entry Deleted Successfully");
                
            }
            else
            {
                if(jTable1.getSelectedRowCount()==0)
                {
                    JOptionPane.showMessageDialog(this,"Table is Empty");
                }    
                else
                {
                    JOptionPane.showMessageDialog(this,"Please Select A Single Entry For Delete");
                }
            }
        }
        catch (SQLException ex) {
                Logger.getLogger(View_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(jRadioButton1.isSelected())
        {    
            if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c))
            {
                jTextField2.setEditable(true);
            }
            else
            {
                jTextField2.setEditable(false);
            }
        }
        else
        {
            if(jRadioButton3.isSelected())
            {
                if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c))
                {
                    jTextField2.setEditable(true);
                }
                else
                {
                    jTextField2.setEditable(false);
                }
            }
            else
            {
                if(jRadioButton4.isSelected())
                {
                    if(Character.isDigit(c) || Character.isISOControl(c))
                    {
                        jTextField2.setEditable(true);
                    }
                    else
                    {
                        jTextField2.setEditable(false);
                    }
                }
                else
                {
                    if(jRadioButton2.isSelected())
                    {
                        jTextField2.setEditable(true);
                    }
                }
        {    
                }
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c))
        {
            jTextField1.setEditable(true);
        }
        else
        {
            jTextField1.setEditable(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jRadioButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1KeyPressed

    private void jRadioButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2KeyPressed

    private void jRadioButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3KeyPressed

    private void jRadioButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4KeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText("");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText("");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText("");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText("");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Tiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Tiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Tiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Tiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Tiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
